version: "3"

tasks:
    all:
        desc: Build the app and the vhs without auth
        cmds:
        - task build
        - task release
        - task no-auth

    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin/mobitag main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go

    clean:
        desc: Remove all retrieved *.png files
        cmds:
        - rm -rf bin/
        - rm -rf dist/
        - rm -rf media/*

    auth:
        desc: Build the vhs with auth
        cmds:
        - vhs mobitag-auth.tape

    no-auth:
        desc: Build the vhs without auth
        cmds:
        - vhs mobitag-no-auth.tape

    release:
        desc: Build all the binaries with goreleaser
        cmds:
        - goreleaser release --snapshot --clean