name: goreleaser

# on push on the main or develop branch only when there is a tag
on:
  push:
    branches: [main, develop]
    tags:
      - '*' # this means any tag

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/') && (github.ref_name == 'main' || github.ref_name == 'develop')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}